// <auto-generated />
using System;
using FitnessApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    partial class FitnessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("FitnessApp.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PackagePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("FitnessApp.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Başlangıç için ideal.",
                            Features = "Haftada 2 Gün Kullanım,Antrenman Programı,Beslenme Programı,7/24 WhatsApp Desteği",
                            ImageUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48",
                            Name = "Basic Paket",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Düzenli spor yapanlar için.",
                            Features = "Haftada 4 Gün Kullanım,Antrenman Programı,Beslenme Programı,Supplement Çekilişi Hakkı",
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
                            Name = "Pro Paket",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tam kapsamlı profesyonel destek.",
                            Features = "Birebir Yüz Yüze Ders,Grup Dersleri,Beslenme & Antrenman Programı,7/24 WhatsApp Desteği,Supplement ve Üyelik Çekilişleri",
                            ImageUrl = "https://images.unsplash.com/photo-1599058945522-28d584b6f0ff",
                            Name = "Elite Paket",
                            Price = 2000m
                        });
                });

            modelBuilder.Entity("FitnessApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            Password = "123",
                            Username = "barkin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
